-- CREATE SEQUENCES

CREATE SEQUENCE Stadium_seq START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE Team_seq START WITH 200 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE Player_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE Sponsor_seq START WITH 300 INCREMENT BY 1 NOCACHE;


-- CREATE TABLES

CREATE TABLE Stadium ( Stadium_ID INT DEFAULT Stadium_seq.NEXTVAL, Stadium_Name VARCHAR(20) NOT NULL, Capacity NUMBER(10), Stadium_Year NUMBER(4), Stadium_City VARCHAR(20) NOT NULL , Review_Score NUMBER(3), State_Stadium VARCHAR(20) DEFAULT 'FUNCTIONAL' NOT NULL);

CREATE TABLE Team (Team_ID INT DEFAULT Team_seq.NEXTVAL, Team_Name VARCHAR(20) NOT NULL, City_Founded VARCHAR(20) NOT NULL, Year_Created NUMBER(4), Team_Goals_Scored NUMBER(10), Goals_Conceded NUMBER(10), Stadium_ID INT);

CREATE TABLE Player (Player_ID INT DEFAULT Player_seq.NEXTVAL, Player_Name VARCHAR(20)  NOT NULL, Player_Surname VARCHAR(20) NOT NULL, Player_Position VARCHAR(3) DEFAULT 'DEF' NOT NULL, Games_Played NUMBER(3), Player_Goals_Scored NUMBER(3), Contract_Value NUMBER(12), Player_Email VARCHAR(40), Player_Country VARCHAR(20) NOT NULL, Date_of_Birth DATE, Team_ID INT NOT NULL);

CREATE TABLE Sponsor (Sponsor_ID INT DEFAULT Sponsor_seq.NEXTVAL, Sponsor_Name VARCHAR(20) NOT NULL, Sponsor_Type VARCHAR(20) NOT NULL, City_Headquarters VARCHAR(20) NOT NULL);

CREATE TABLE Sponsorship (Sponsor_ID INT NOT NULL, Team_ID INT NOT NULL, Fee NUMBER(10));



