-- DROP

-- 1. DROP TABLES

DROP TABLE SPONSORSHIP CASCADE CONSTRAINTS;
DROP TABLE PLAYER CASCADE CONSTRAINTS;
DROP TABLE TEAM CASCADE CONSTRAINTS;
DROP TABLE SPONSOR CASCADE CONSTRAINTS;
DROP TABLE STADIUM CASCADE CONSTRAINTS;

-- 2. DROP SEQUENCES

DROP SEQUENCE Stadium_seq;
DROP SEQUENCE Team_seq;
DROP SEQUENCE Player_seq;
DROP SEQUENCE Sponsor_seq;