-- QUERIES

-- a) 
SELECT * FROM TEAM;
--b)
 SELECT TEAM_NAME, TEAM_GOALS_SCORED, GOALS_CONCEDED FROM TEAM ORDER BY TEAM_NAME DESC;
--c1)
 SELECT * FROM PLAYER WHERE PLAYER_COUNTRY = 'FRANCE' AND PLAYER_NAME LIKE 'F%';
-- c2)
SELECT * FROM PLAYER WHERE PLAYER_COUNTRY NOT  LIKE 'FRANCE' AND DATE_OF_BIRTH BETWEEN '30-JAN-1999' AND '31-DEC-2000';
--d1)
 SELECT TEAM_NAME, PLAYER_SURNAME FROM TEAM JOIN PLAYER ON TEAM.TEAM_ID = PLAYER.TEAM_ID;
-- d2)
SELECT STADIUM_NAME, TEAM_NAME, PLAYER_SURNAME FROM STADIUM JOIN TEAM ON STADIUM.STADIUM_ID = TEAM.STADIUM_ID JOIN PLAYER ON TEAM.TEAM_ID = PLAYER.TEAM_ID;
--d3)
SELECT PLAYER_SURNAME, TEAM_NAME, SPONSOR_NAME, FEE FROM PLAYER JOIN TEAM ON PLAYER.TEAM_ID = TEAM.TEAM_ID JOIN SPONSORSHIP ON TEAM.TEAM_ID = SPONSORSHIP.TEAM_ID JOIN SPONSOR ON SPONSORSHIP.SPONSOR_ID = SPONSOR.SPONSOR_ID;
--e)
-- 1.
SELECT PLAYER_NAME, PLAYER_SURNAME FROM PLAYER WHERE PLAYER_SURNAME LIKE 'K%S'; 
--2.
SELECT TEAM_NAME, COUNT(*) AS TOTAL_PLAYERS FROM TEAM JOIN PLAYER ON TEAM.TEAM_ID = PLAYER.TEAM_ID GROUP BY TEAM_NAME;
--3.
SELECT PLAYER_NAME, PLAYER_SURNAME, CONTRACT_VALUE FROM PLAYER WHERE CONTRACT_VALUE = (SELECT MAX(CONTRACT_VALUE) FROM PLAYER);
--4.
SELECT COUNT(*) AS LOW_REVIEW_STADIUMS FROM STADIUM WHERE REVIEW_SCORE < 2;
--5. 
SELECT PLAYER_SURNAME, PLAYER_NAME, TEAM_NAME FROM PLAYER JOIN TEAM ON PLAYER.TEAM_ID = TEAM.TEAM_ID ORDER BY PLAYER_SURNAME;
--6.
SELECT PLAYER_SURNAME, PLAYER_NAME, TEAM_NAME, PLAYER_GOALS_SCORED FROM PLAYER JOIN TEAM ON PLAYER.TEAM_ID=TEAM.TEAM_ID WHERE PLAYER_GOALS_SCORED = (SELECT MAX(PLAYER_GOALS_SCORED) FROM PLAYER);
--7.
SELECT CITY_FOUNDED, COUNT(*) AS NUMBER_OF_TEAMS FROM TEAM GROUP BY CITY_FOUNDED;
--8. 
SELECT TEAM_NAME, (TEAM_GOALS_SCORED - GOALS_CONCEDED) AS DIFF FROM TEAM WHERE  (TEAM_GOALS_SCORED- GOALS_CONCEDED= (SELECT MIN(TEAM_GOALS_SCORED - GOALS_CONCEDED) FROM TEAM));
--9.
SELECT COUNT(STADIUM_NAME) FROM STADIUM WHERE STADIUM_YEAR BETWEEN 1980 AND 1999;
--10.
SELECT PLAYER_SURNAME, PLAYER_NAME FROM PLAYER WHERE TO_CHAR(DATE_OF_BIRTH,'MM') = '07';
--11.
SELECT COUNT(*) FROM STADIUM LEFT JOIN TEAM ON STADIUM.STADIUM_ID = TEAM.STADIUM_ID WHERE TEAM.TEAM_ID IS NULL;
--12.
SELECT TEAM_NAME FROM TEAM WHERE TEAM_NAME LIKE '%SAINT%';
--13.
SELECT PLAYER_NAME, PLAYER_SURNAME, CONTRACT_VALUE, PLAYER_GOALS_SCORED FROM PLAYER WHERE PLAYER_COUNTRY='BRAZIL' AND (CONTRACT_VALUE = ( SELECT MAX(CONTRACT_VALUE) FROM PLAYER WHERE PLAYER_COUNTRY = 'BRAZIL') OR PLAYER_GOALS_SCORED = (SELECT MAX(PLAYER_GOALS_SCORED) FROM PLAYER WHERE PLAYER_COUNTRY = 'BRAZIL'));
--14.
SELECT PLAYER_SURNAME, PLAYER_NAME, PLAYER_POSITION, CONTRACT_VALUE FROM PLAYER WHERE( CONTRACT_VALUE IN (SELECT MAX(CONTRACT_VALUE) FROM PLAYER GROUP BY PLAYER_POSITION));
--15. 
SELECT PLAYER_NAME, PLAYER_SURNAME, SUBSTR (PLAYER_COUNTRY,1,2)||SUBSTR (PLAYER_NAME,1,4)||SUBSTR (PLAYER_SURNAME,1,4)AS PLAYER_USERNAME FROM PLAYER;
--16.
SELECT SUM(CONTRACT_VALUE) FROM PLAYER;
--17.
 SELECT SPONSOR_NAME, (SUM(FEE)) FROM SPONSOR JOIN SPONSORSHIP ON SPONSOR.SPONSOR_ID = SPONSORSHIP.SPONSOR_ID GROUP BY SPONSOR_NAME HAVING SUM(FEE) = (SELECT MAX(SUM(FEE)) FROM SPONSORSHIP GROUP BY SPONSOR_ID);
--18.
SELECT SPONSOR_TYPE , SUM(FEE) FROM SPONSOR JOIN SPONSORSHIP ON SPONSOR.SPONSOR_ID = SPONSORSHIP.SPONSOR_ID GROUP BY SPONSOR_TYPE ORDER BY SUM(FEE) DESC FETCH FIRST 1 ROW ONLY;
--19.
SELECT SPONSOR_NAME, PLAYER_NAME, PLAYER_SURNAME, CONTRACT_VALUE FROM PLAYER JOIN SPONSORSHIP ON PLAYER.TEAM_ID = SPONSORSHIP.TEAM_ID JOIN SPONSOR ON SPONSORSHIP.SPONSOR_ID = SPONSOR.SPONSOR_ID WHERE (SPONSORSHIP.SPONSOR_ID, CONTRACT_VALUE) IN (SELECT SPONSORSHIP.SPONSOR_ID, MAX(CONTRACT_VALUE) FROM PLAYER JOIN SPONSORSHIP ON PLAYER.TEAM_ID = SPONSORSHIP.TEAM_ID GROUP BY SPONSORSHIP.SPONSOR_ID);
--20.
SELECT DISTINCT TEAM_NAME, FEE FROM TEAM JOIN SPONSORSHIP ON SPONSORSHIP.TEAM_ID = TEAM.TEAM_ID JOIN SPONSOR ON SPONSOR.SPONSOR_ID = SPONSORSHIP.SPONSOR_ID WHERE SPONSOR_TYPE = 'ELECTRONICS' ORDER BY FEE DESC FETCH FIRST 1 ROW ONLY;

